server:
  port: 8084

spring:
  application:
    name: group-service
  datasource:
    url: ${GROUP_DB_URL:jdbc:postgresql://postgres:5432/micro_service_group_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://service-registry:8761/eureka/}
