server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: redis-11781.crce263.ap-south-1-1.ec2.cloud.redislabs.com
      port: 11781
      password: c6iBDzGsQz922Ocvt496JvAYr8n4fxAn
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: group-service
          uri: lb://group-service
          predicates:
            - Path=/api/groups/**

        - id: expense-service
          uri: lb://expense-service
          predicates:
            - Path=/api/expenses/**
          filters:
            - name: SlidingWindowRateLimit
              args:
                limit: 2
                windowSeconds: 60

        - id: dashboard-service
          uri: lb://dashboard-service
          predicates:
            - Path=/api/dashboard/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
